# Page settings

baseURL = "https://proochista.github.io/cv/"
languageCode = "en"
title = "Proochista Ariana Résumé"
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "docs"




[params]
    author = ""
    description = ""


    primaryColor = "#002147"
    textPrimaryColor = "#292929"




    [params.profile]
        enable = true
        name = "Proochista Ariana"
        tagline = "Director of MSc in International Health and Tropical Medicine, Group Head / PI, Member of congregation, Supervisor and Unit Director"
        avatar = "proochista.jpg"







    [params.contact]
        enable = true
        location = "Oxford, United Kingdom"

        [[params.contact.list]]
        icon = "fab fa-skype"
        url = "skype:proochista?call"
        text = "proochista"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:proochista.ariana@ndm.ox.ac.uk"
        text = "proochista.ariana@ndm.ox.ac.uk"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://proochista.org"
        text = "https://proochista.org"







    [params.skills]
        enable = false

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = ""
        [[params.skills.list.items]]
        details = ""
        [[params.skills.list.items]]
        details = ""
        [[params.skills.list.items]]
        details = ""
        [[params.skills.list.items]]
        details = ""
        [[params.skills.list.items]]
        details = ""
        [[params.skills.list.items]]
        details = ""

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = ""
        [[params.skills.list.items]]
        details = ""
        [[params.skills.list.items]]
        details = ""
        [[params.skills.list.items]]
        details = ""








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Post Graduate Diploma in Learning and Teaching in Higher Education"
        university = "Oxford University"
        dates = "2009"
        [[params.education.list]]
        degree = "DPhil in International Development"
        university = "Oxford University"
        dates = "2008"
        [[params.education.list]]
        degree = "MS in International Health"
        university = "Harvard University"
        dates = "1998"
        [[params.education.list]]
        degree = "Master in Public Health"
        university = "Oregon Health Science University"
        dates = "1997"
        [[params.education.list]]
        degree = "Bachelor of Arts (with a major in Immunology)"
        university = "Reed College"
        dates = "1993"        








    [params.awards]
        enable = true

        [[params.awards.list]]
        name = "Major Educator Award"
        body = "Medical Sciences Division, University of Oxford"
        date = "2019"
        [[params.awards.list]]
        name = "Outstanding Graduate Supervisor Award - Medical Sciences Division"
        body = "Oxford University Student Union"
        date = "2017"
        [[params.awards.list]]
        name = "Special Recognition Award"
        body = "Oxford University Student Union"
        date = "2017"
        [[params.awards.list]]
        name = "Most Acclaimed Lecturer - Medical Sciences Division"
        body = "Oxford University Student Union"
        date = "2016"
        [[params.awards.list]]
        name = "Excellent Teacher Award"
        body = "Medical Sciences Division, University of Oxford"
        date = "2013"
        [[params.awards.list]]
        name = "Most Acclaimed Lecturer - Medical Sciences Division"
        body = "Oxford University Student Union"
        date = "2013"
        [[params.awards.list]]
        name = "George Webb Medley Research Award"
        body = "Department of Economics, University of Oxford"
        date = "2004"
        [[params.awards.list]]
        name = "Norman Chester Research Award"
        body = "Department of Politics, University of Oxford"
        date = "2004"
        [[params.awards.list]]
        name = "George Peters Travel Award"
        body = "Queen Elizabeth House, University of Oxford"
        date = "2004"
        [[params.awards.list]]
        name = "Travel Award"
        body = "Oxford University Mexican Centre"
        date = "2004"






    [params.languages]
        enable = false

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "Spanish"
        level = "Professional"








    [params.interests]
        enable = false

        [[params.interests.list]]
        name = "Climbing"
        [[params.interests.list]]
        name = "Snowboarding"
        [[params.interests.list]]
        name = "Photography"
        [[params.interests.list]]
        name = "Travelling"








    [params.summary]
        enable = true
        text = "I am Course Director for the MSc in International Health and Tropical Medicine, Centre for Tropical Medicine and Global Health, Nuffield Department of Medicine. My research empirically examines the relationship between processes of development and health in resource limited and transition contexts, appreciating the multidimensionality of both."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Director, MSc in International Health and Tropical Medicine"
        dates = "2015 - Present"
        company = "Nuffield Department of Medicine, University of Oxford"
        details = ""

        [[params.experience.list]]
        title = "Deputy Director, Grand Union Doctoral Training Partnership"
        dates = "2017 - 2019"
        company = "Social Sciences Division, University of Oxford"
        details = ""

        [[params.experience.list]]
        title = "Educational Development Consultant"
        dates = "2014-2015"
        company = "Oxford Learning Institute, University of Oxford"
        details = ""

        [[params.experience.list]]
        title = "Departmental Lecturer in Global Health and Development"
        dates = "2008 - 2015"
        company = "Department of International Development, University of Oxford"
        details = ""

        [[params.experience.list]]
        title = "Director, MSc in Global Health Science"
        dates = "2010 - 2014"
        company = "Department of Public Health, University of Oxford"
        details = ""

        [[params.experience.list]]
        title = "Teaching and Research Associate"
        dates = "2007 - 2008"
        company = "Department of Public Health, University of Oxford"
        details = ""

        [[params.experience.list]]
        title = "Teaching and Research Assistant"
        dates = "2006 - 2007"
        company = "Department of Public Health, University of Oxford"
        details = ""

        [[params.experience.list]]
        title = "UNDP Human Development Training Course coordinator"
        dates = "2004; 2006; 2008"
        company = "United Nations Development Programme"
        details = ""

        [[params.experience.list]]
        title = "Researcher"
        dates = "2006 - 2007"
        company = "Oxford Poverty and Human Development Initiative"
        details = ""





    [params.teaching]
        enable = true

        [[params.teaching.list]]
        title = "Medical Sciences Division Teacher Training"
        meta = "University of Oxford"
        tagline = "Teaching Skills Workshops"

        [[params.teaching.list]]
        title = "Teacher Training"
        meta = "Oxford Tropical Network"
        tagline = "Teaching and supervision workshops delivered for participants in Kenya Medical Research Insitute, Mahidol Oxford Tropical Medicine Research Unit, Shoklo Malaria Research Unit, Oxford University Clinical Research Unit"

        [[params.teaching.list]]
        title = "Introduction to Teaching at Oxford"
        meta = "Oxford Learning Institute, University of Oxford"
        tagline = "Part of induction programme for new lecturers at University of Oxford"

        [[params.teaching.list]]
        title = "International Development and Health"
        meta = "University of Oxford"
        tagline = "A module offered to post-graduate students in International Health and Tropical Medicine, University of Oxford"
        
        [[params.teaching.list]]
        title = "Health, Environment and Development"
        meta = "University of Oxford"
        tagline = "A module offered to post-graduate students in International Health and Tropical Medicine and Geography, University of Oxford"        

        [[params.teaching.list]]
        title = "Social Determinants of Health and Global Burden of Disease"
        meta = "University of Oxford"
        tagline = "Core lecture for MSc students in International Health and Tropical Medicine, University of Oxford"        

        [[params.teaching.list]]
        title = "Poverty and Health"
        meta = "University of Oxford"
        tagline = "Lecture for Graduate Entry Medical Students, University of Oxford"

        [[params.teaching.list]]
        title = "International Development and Health and Research Ethics"
        meta = "University of Oxford"
        tagline = "Lecture for post-graduate students in International Development, University of Oxford"







    [params.publications]
        enable = true

        [[params.publications.list]]
        title = "Journal Articles"
        [[params.publications.list.items]]
        details = "Zhu Jiming and Ariana P (2019) Provider Perspectives on General Practice in Henan, China: a mixed-methods study. BMJ Open (in press)"
        [[params.publications.list.items]]
        details = "Marzouk M, Kelley M, Fadhil I, Slama S, Longuere K-S, Ariana P, Carson G and Marsh V. (2019) 'If I have a cancer, it is not my fault I am a refugee': A qualitative study with expert stakeholders on cancer care management for Syrian refugees in Jordan. PLoS ONE 14(9): e0222496. https://doi.org/10.1371/journal.pone.0222496"
        [[params.publications.list.items]]
        details = "Haenssgen MJ, Charoenboon N, Zanello G… Ariana P (2019).  Antibiotic knowledge, attitudes and practices: new insights from cross-sectional rural health behaviour surveys in low-income and middle-income South-East Asia BMJ Open 2019;9:e028224. doi: 10.1136/bmjopen-2018-028224"
        [[params.publications.list.items]]
        details = "Haenssgen MJ, Charoenboon N, Zanello G, Mayxay M, Reed-Tsochas F, Jones COH, Kosaikanont R, Praphattong P, Manohan P, Lubell Y,… Ariana P (2018). Antibiotics and activity spaces: protocol of an exploratory study of behaviour, marginalisation and knowledge diffusion. BMJ Glob Health, 3 (2), pp. e000621."
        [[params.publications.list.items]]
        details = "Haenssgen MJ and Ariana P (2018). The place of technology in the capability approach. Oxford Development Studies.  doi: 10.1080/13600818.2017.1325456"
        [[params.publications.list.items]]
        details = "Wertheim HFL, Chuc NTK, Punpuing S, Khan WA, Gyapong M, Asante KP, Munguambe K, Gómez-Olivé FX, Ariana P, John-Langba J et al (2017). Community-level antibiotic access and use (ABACUS) in low- and middle-income countries: Finding targets for social interventions to improve appropriate antimicrobial use - an observational multi-centre study. Wellcome Open Res, 2 pp. 58."
        [[params.publications.list.items]]
        details = "Haenssgen MJ and Ariana P (2017). The social implications of technology diffusion: uncovering the unintended consequences of people’s health-related mobile phone use in rural India and China. World Development. doi: 10.1016/j.worlddev.2017.01.014"
        [[params.publications.list.items]]
        details = "Haenssgen MJ and Ariana P (2017). Healthcare access: a sequence-sensitive approach. Social Science & Medicine – Population Health, 3, 37-47. doi: 10.1016/j.ssmph.2016.11.008"
        [[params.publications.list.items]]
        details = "Radin, E, Ariana P, Broekel T and Tran TK (2016). “Analyzing demand-side efficiency in global health: an application to maternal care in Vietnam” Health policy and planning, p.czw063."
        [[params.publications.list.items]]
        details = "Preston, E.C., Ariana, P., Penny, M.E., Frost, M. and Plugge, E., (2015). “Prevalence of childhood overweight and obesity and associated factors in Peru” Rev Panam Salud Publica 38(6)"
        [[params.publications.list.items]]
        details = "Nair M, Ariana P, Webster P (2014) “Impact of mothers' employment on infant feeding and care: a qualitative study of the experiences of mothers employed though the Mahatma Gandhi National Rural Employment Guarantee Act” BMJ Open 2014:4 e004434"
        [[params.publications.list.items]]
        details = "Xiangshu, D., Ariana, P. and Xiang, X., (2013). “An Investigation of Chinese Rural Doctors' Job Quit Intention: Empirical Analysis of Income Satisfaction, Hospital Organization Satisfaction and Doctor-patient Relationship”. Economic Review 2, 5."
        [[params.publications.list.items]]
        details = "Nair M, Ariana P, Ohuma E, Gray R, De Stavola B, Webster P (2013) “Effect of the Mahatma Gandhi National Rural Employment Guarantee Act (MGNREGA) on malnutrition of infants in Rajasthan, India: a mixed methods study” Plos One 8(9) e75089"
        [[params.publications.list.items]]
        details = "Nair M, Ariana, P, Webster P (2012) “The decision to use institutions for delivery:  A study among economically deprived women in Andhra Pradesh, India” Rural and Remote Health 12:2311."
        [[params.publications.list.items]]
        details = "Barnett I, Ariana P, Petro S, Penny M, Plugge E, Boyden J. (2012) “Cohort Profile:  The Young Lives Study ” International Journal of Epidemiology doi: 10.1093/ije/dys082"
        [[params.publications.list.items]]
        details = "Ariana, P (2012) “Challenging our Understanding of Health: Indigenous perspectives from the Highlands of Chiapas, Mexico” Oxford Development Studies 40(3), 405-21."
        [[params.publications.list.items]]
        details = "Nair M., Webster P, Ariana P (2011) “Impact of non-health Policies on Infant Mortality through the Social Determinants Pathway” Bulletin of the World Health Organisation 89(11), 778."
        [[params.publications.list.items]]
        details = "Fukuda-Parr, S. and Ariana, P (2011) “Health Impact Fund–Raising Issues of Distribution, IP Rights and Alliances” Intellectual Property Watch."
        [[params.publications.list.items]]
        details = "McHardy K., Ariana P, Plugge E. (2011) “Public Health in Practice:  Translating Theory into Action”  Medical Education 45(11), 1142."
        
        [[params.publications.list]]
        title = "Books"        
        [[params.publications.list.items]]
        details = "Ariana, P and Naveed, A (2009) “Health” in Deneulin S (ed) An Introduction to the Human Development and Capability Approach, Earthscan."
        
        [[params.publications.list]]
        title = "Papers"        
        [[params.publications.list.items]]
        details = "Ariana, P (2007) “Health Inequalities in America” Background paper for American Human Development Report 2008-2009. "

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/proochista"
        title = "proochista"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/proochistaariana"
        title = "proochistaariana"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/intdevhealth"
        title = "@intdevhealth"





